repos:
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.0
    hooks:
    -   id: flake8
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
    -   id: bandit
        exclude: ^tests/
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.782
  hooks:
    - id: mypy
      exclude: ^docs/  # keep in sync with mypy.ini
