repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.12.0
  hooks:
    # Run the linter, organize imports
    - id: ruff-check
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.15.0
  hooks:
    - id: mypy
      exclude: ^docs/  # keep in sync with mypy.ini
      additional_dependencies: [types-requests]
- repo: https://github.com/RobertCraigie/pyright-python
  rev: v1.1.402
  hooks:
    - id: pyright
