language: python
dist: xenial
sudo: false

env:
  global:
    - secure: WryNWQbqvl0b3LkQB3WQ9qYUhwkPoBeZC2BD2o6bwRWsvWWXR9Utj+jEvXj9XcQ/T+Vuy/S25mAhQidGiLQY8yMuOknJFAFeHtQ1BEBsfQkM8NXO0HgAiQMi7ZSszN1yu6seQvjXyfmwA9tmAO/bT1u22lGvOK1/JGY29zMrJNXy/OXk0m3DFpUxK65d3t8ck+vGFg0QzfWNjGfqd/MgN9iKc6OXMZBdWbZECkOtAOuubauUiQBMQcLFOx+nryj81AwBm/nyoYpb0DusmsD3mCDY8KdmJroO+D+GSoBAALBzKLmaOQaMRVXMu1HySki50K90T+UTBwf8S4m3cV1poP0zjvRggkeTtsW2VqnO89vV5J5rasfQWqb99xHnZO72VQ2ZuIqJBcA+H9JkEqTI9FJKe4Fa5+8JV4I7aHWdQVhG824yIG9IbvXi8YTM6vttgFktZ19qTDjkP+xYi+ArR1PvDeyOJhfHY9/8MFQfQ67033pbF1o5pMlanC/avnSGJTj7qUkLbUAIR53G3/C9ntGTJT8ECBOd/Dc9GzBGlQtK5KpgAn8mQ+3yoZE2Qm2FjXbNkghL6DObjUpA2SNZF9MNdND73CIflMs+/wNcOmekLxM74yLaKz9iMBtXNxZXaM8H7oqRowVBQ2Ze3JtPlO7ruibVIZ/6Hel+PSQLo9w=

addons:
  apt:
    packages:
      - libffi-dev
      - libssl-dev
      - swig

matrix:
  include:
    - os: linux
      python: 2.7
      env:
        - DISPATCHER="ON"
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: linux
      python: 3.7
      env:
        - DISPATCHER="ON"
    - os: linux
      python: pypy2.7-6.0
    - os: linux
      python: pypy3.5-6.0
    - os: osx
      language: generic
      osx_image: xcode10.1
      sudo: required
      env:
        - DISPATCHER="ON"

cache:
  directories:
    - $HOME/.cache/pip

before_install:
  - openssl aes-256-cbc -k "$tlspwd" -md sha256 -in ./.ci/client-combined.pem.enc -out ./.ci/client-combined.pem -d

install:
  - pip install pre-commit
  - pip install -e .[http]

script:
  - |
    if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]] || [[ "$TRAVIS_PYTHON_VERSION" == "3.7" ]]
    then
      pre-commit run --all-files
    fi
  - export BACKEND="NONE"
  - |
    if [[ "$DISPATCHER" == "ON" ]]
    then
      export krnl="$(uname -s | tr '[:upper:]' '[:lower:]')"
      wget https://github.com/square/ghostunnel/releases/download/v1.3.1/ghostunnel-v1.3.1-$krnl-amd64-with-pkcs11 -O ghostunnel
      chmod +x ./ghostunnel
      ./ghostunnel client --listen localhost:12345 --target hsm-connector01.sthlm.in.yubico.org:8443 --keystore ./.ci/client-combined.pem --cacert ./.ci/server-crt.pem 2>/dev/null &
      sleep 3
      export BACKEND="$(curl http://localhost:12345/dispatcher/request)"
      echo BACKEND=$BACKEND
    fi
  - python setup.py test

after_script:
  - |
    if [[ "$DISPATCHER" == "ON" ]]
    then
      curl "http://localhost:12345/dispatcher/release?connector=$BACKEND"
    fi
